### ISSUE TITLE
I can't quit Pd if I load py

### ISSUE THREAD

**Issue by alexdrymonitis** [SopiMlab/DeepLearningWithAudio#5]
Whether I put py from DeepLearningWithAudio in the startup paths and libraries or I use `[declare -path py -lib py]` I cannot quit Pd. The library loads fine and Pd functions properly, it just won't quit.
Launching Pd with gdb I get this when trying to quit:
```
Thread 1 "pd" received signal SIGHUP, Hangup.
futex_wait (private=<optimized out>, expected=12, futex_word=0x7ffff693126c <pybase::qucond+76>) at ../sysdeps/nptl/futex-internal.h:146
146     ../sysdeps/nptl/futex-internal.h: No such file or directory.
```
I'm on UbuntuStudio 21.04 with Pd-0.51.4

**Comment by ahihi** [comment]
we're tracking this bug in https://github.com/SopiMlab/py/issues/2 so i'm closing this one. the gdb info is good to have, though at the moment i have no idea what it means 😅
